# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  ru: Your awesome title
  en: Votre titre génial
email: your-email@domain.com
description:
  ru: Талер. Первая Белорусская криптовалюта создана для использования в бизнесе и обычными людьми. Телер это новый биткоин.
  en: Taler. First Belarus cryptocurrency. Taler already used by businesses in Belarus and local peopple.
index:
  ru: index.html
  en: index_en.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tlrbtc.com/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
