# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  ru: Талер - белорусский Биткоин
  en: Taler cryptocurrency of the future
email: talerdev@protonmail.com
description:
  ru: Анонимная криптовалюта с открытым кодом, стабильность на рынке, многофункциональность и бизнес-партнеры среди ведущих белорусских компаний. Частные расчеты, накопительная функция и реальное применение - это Талер. Ваша валюта будущего.
  en: Anonymous cryptocurrency with open code, market stability, multifunctionality and business partners amongst leading Belarusian companies. Private payments, accumulating function and real-life adoption. This is Taler. Your future currency.
index:
  ru: index.html
  en: index_en.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tlrbtc.com" # the base hostname & protocol for your site
production_url: "https://tlrbtc.com"

# Build settings
markdown: kramdown
